import 'reflect-metadata';
import { after, before, test } from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { NestExpressApplication } from '@nestjs/platform-express';
import sharp from 'sharp';
import { Db } from '../src/db';
import { createApp } from '../src/app';
import { normalize } from '../src/auth';
process.env.NODE_ENV='test';
process.env.DEV_OTP='true';
process.env.JWT_SECRET='test-secret-with-at-least-32-characters';
let app:NestExpressApplication;
let db:Db;
let http:ReturnType<typeof request>;
type Account={id:string;token:string};
const accounts:Account[]=[];
let itemA:string,itemB:string,shop:string,match:string;
const base={title:'Nice denim jacket',description:'Good condition, ready for a new home.',category:'CLOTHES',condition:'GOOD',sell:true,swap:true,price:100,swapValue:100,area:'Osu',latitude:5.56,longitude:-0.18};
function as(user:Account) { return {Authorization:`Bearer ${user.token}`}; }
async function login(value:string):Promise<Account> {
  const c=await http.post('/auth/request').send({type:'EMAIL',value}).expect(201);
  assert.match(c.body.devCode,/^\d{6}$/);
  const v=await http.post('/auth/verify').send({challengeId:c.body.challengeId,code:c.body.devCode}).expect(201);
  return {id:v.body.user.id,token:v.body.token};
}
async function listing(user:Account,extra:Record<string,unknown>={}) {
  const photo=await sharp({create:{width:8,height:8,channels:3,background:'#FFB020'}}).jpeg().toBuffer();
  const upload=await http.post('/uploads').set(as(user)).attach('photos',photo,'item.jpg').expect(201);
  const result=await http.post('/items').set(as(user)).send({...base,photos:upload.body.photos,...extra}).expect(201);
  return result.body.id as string;
}
before(async()=>{
  if(!process.env.DATABASE_URL?.includes('havana_test')) throw new Error('Tests require a dedicated database URL containing havana_test.');
  app=await createApp();await app.init();db=app.get(Db);http=request(app.getHttpServer());
  await db.$executeRawUnsafe('TRUNCATE TABLE "users" CASCADE');
  await db.otpChallenge.deleteMany();
});
after(async()=>{await app?.close();});
test('health, normalization, authentication, validation and OTP replay protection',async()=>{
  await http.get('/health').expect(200);
  await http.get('/me').expect(401);
  assert.equal(normalize('PHONE','054 123 4567'),'+233541234567');
  await http.post('/auth/request').send({type:'PHONE',value:'wrong'}).expect(400);
  const c=await http.post('/auth/request').send({type:'PHONE',value:'0541234567'}).expect(201);
  await http.post('/auth/verify').send({challengeId:c.body.challengeId,code:c.body.devCode==='000000'?'111111':'000000'}).expect(401);
  const v=await http.post('/auth/verify').send({challengeId:c.body.challengeId,code:c.body.devCode}).expect(201);
  accounts.push({id:v.body.user.id,token:v.body.token});
  await http.post('/auth/verify').send({challengeId:c.body.challengeId,code:c.body.devCode}).expect(401);
  for(const email of ['b@test.com','c@test.com','d@test.com']) accounts.push(await login(email));
  const me=await http.get('/me').set(as(accounts[0])).expect(200);
  assert.equal(me.body.identities[0].value,'+233541234567');
  await http.patch('/me').set(as(accounts[0])).send({name:'Ama'}).expect(200);
});
test('backup identity proves ownership and signs into the same account',async()=>{
  const a=accounts[0];
  const c=await http.post('/auth/link/request').set(as(a)).send({type:'EMAIL',value:'backup@test.com'}).expect(201);
  await http.post('/auth/verify').send({challengeId:c.body.challengeId,code:c.body.devCode}).expect(401);
  const linked=await http.post('/auth/link/verify').set(as(a)).send({challengeId:c.body.challengeId,code:c.body.devCode}).expect(201);
  assert.equal(linked.body.user.id,a.id);
  const again=await login('backup@test.com');assert.equal(again.id,a.id);
  await http.post('/auth/link/request').set(as(accounts[1])).send({type:'EMAIL',value:'backup@test.com'}).expect(400);
});
test('photo upload, listing ownership, feed filters, saving and mode separation',async()=>{
  const [a,b,c]=accounts;
  await http.post('/items').set(as(a)).send({...base,photos:['/uploads/not-mine.jpg']}).expect(400);
  itemA=await listing(a);itemB=await listing(b,{title:'Kofi jacket'});
  await http.patch(`/items/${itemA}/status`).set(as(b)).send({status:'SOLD'}).expect(403);
  const feed=await http.get('/feed?mode=SHOP&category=CLOTHES').set(as(a)).expect(200);
  assert.equal(feed.body.items.length,1);assert.equal(feed.body.items[0].id,itemB);
  await http.get(`/items/${itemB}`).set(as(a)).expect(200);
  await http.post('/swipes').set(as(c)).send({itemId:itemB,mode:'SWAP',direction:'RIGHT'}).expect(400);
  await http.post('/swipes').set(as(a)).send({itemId:itemB,mode:'SHOP',direction:'RIGHT'}).expect(201);
  assert.equal((await http.get('/saved').set(as(a))).body.length,1);
  assert.equal((await http.get('/feed?mode=SHOP').set(as(a))).body.items.length,0);
  assert.equal((await http.get('/feed?mode=SWAP').set(as(a))).body.items.length,1);
  await http.post('/items').set(as(a)).send({...base,price:1.5,photos:['x']}).expect(400);
});
test('reciprocal concurrent swipes create exactly one match and require two confirmations',async()=>{
  const [a,b,c]=accounts;
  const responses=await Promise.all([http.post('/swipes').set(as(a)).send({itemId:itemB,mode:'SWAP',direction:'RIGHT'}),http.post('/swipes').set(as(b)).send({itemId:itemA,mode:'SWAP',direction:'RIGHT'})]);
  responses.forEach(r=>assert.equal(r.status,201));
  const matches=await db.conversation.findMany({where:{swapItemId:{not:null}}});assert.equal(matches.length,1);match=matches[0].id;
  await http.get(`/conversations/${match}/messages`).set(as(c)).expect(403);
  await http.post(`/conversations/${match}/swap`).set(as(a)).send({action:'DONE'}).expect(400);
  for(const u of [a,b]) await http.post(`/conversations/${match}/swap`).set(as(u)).send({action:'AGREE'}).expect(201);
  await http.post(`/conversations/${match}/swap`).set(as(a)).send({action:'DONE'}).expect(201);
  assert.equal((await db.item.findUniqueOrThrow({where:{id:itemA}})).status,'LIVE');
  await http.post(`/conversations/${match}/swap`).set(as(b)).send({action:'DONE'}).expect(201);
  assert.equal((await db.item.findUniqueOrThrow({where:{id:itemA}})).status,'SWAPPED');
  assert.equal((await db.item.findUniqueOrThrow({where:{id:itemB}})).status,'SWAPPED');
  await http.post(`/conversations/${match}/swap`).set(as(b)).send({action:'DONE'}).expect(201);
});
test('chat, counteroffers, recipient-only acceptance and competing reservations',async()=>{
  const [a,b,c]=accounts;
  const sale=await listing(b,{swap:false});
  shop=(await http.post('/conversations').set(as(a)).send({itemId:sale}).expect(201)).body.id;
  const again=await http.post('/conversations').set(as(a)).send({itemId:sale}).expect(201);assert.equal(again.body.id,shop);
  await http.post(`/conversations/${shop}/messages`).set(as(a)).send({text:'Hi, still available?'}).expect(201);
  await http.post(`/conversations/${shop}/messages`).set(as(b)).send({text:'Yes!'}).expect(201);
  const old=await http.post(`/conversations/${shop}/offers`).set(as(a)).send({amount:70}).expect(201);
  const counter=await http.post(`/conversations/${shop}/offers`).set(as(b)).send({amount:90}).expect(201);
  assert.equal((await db.message.findUniqueOrThrow({where:{id:old.body.id}})).offerStatus,'COUNTERED');
  await http.post(`/conversations/${shop}/offers/${counter.body.id}`).set(as(b)).send({action:'ACCEPT'}).expect(400);
  const second=(await http.post('/conversations').set(as(c)).send({itemId:sale})).body.id;
  const other=await http.post(`/conversations/${second}/offers`).set(as(c)).send({amount:95}).expect(201);
  const results=await Promise.all([http.post(`/conversations/${shop}/offers/${counter.body.id}`).set(as(a)).send({action:'ACCEPT'}),http.post(`/conversations/${second}/offers/${other.body.id}`).set(as(b)).send({action:'ACCEPT'})]);
  assert.deepEqual(results.map(r=>r.status).sort(),[201,400]);
  assert.equal((await db.item.findUniqueOrThrow({where:{id:sale}})).status,'RESERVED');
  await http.get(`/conversations/${shop}/messages`).set(as(a)).expect(200);
  await http.get('/conversations').set(as(a)).expect(200);
  await http.patch(`/items/${sale}/status`).set(as(b)).send({status:'SOLD'}).expect(200);
});
test('ratings need a two-way chat and reports count distinct reporters',async()=>{
  const [a,b,c,d]=accounts;
  await http.post('/ratings').set(as(c)).send({toId:a.id,stars:5}).expect(403);
  await http.post('/ratings').set(as(a)).send({toId:b.id,stars:5}).expect(201);
  await http.post('/ratings').set(as(a)).send({toId:b.id,stars:4}).expect(201);
  const me=await http.get('/me').set(as(b));assert.equal(me.body.rating,4);assert.equal(me.body.ratingCount,1);
  const target=await listing(b);
  for(const u of [a,a,c]) await http.post(`/items/${target}/report`).set(as(u)).send({reason:'Misleading listing details'}).expect(201);
  assert.equal((await db.item.findUniqueOrThrow({where:{id:target}})).hidden,false);
  await http.post(`/items/${target}/report`).set(as(d)).send({reason:'Misleading listing details'}).expect(201);
  await http.get(`/items/${target}`).set(as(a)).expect(404);
});
test('profile location, empty-closet pass, unsave, incremental polling and inbox match flags',async()=>{
  const [,b,c,d]=accounts;
  await http.patch('/me').set(as(d)).send({latitude:5.668}).expect(400);
  const me=await http.patch('/me').set(as(d)).send({area:'Madina',latitude:5.668,longitude:-0.164}).expect(200);
  assert.equal(me.body.area,'Madina');
  const x=await listing(b,{title:'Polling test item'});
  // Saved Madina location is the feed default (Osu item is ~12 km away, central Accra would be ~5 km).
  const feed=await http.get('/feed?mode=SHOP').set(as(d)).expect(200);
  assert.ok(feed.body.items.find((i:{id:string})=>i.id===x).distanceKm>10);
  await http.post('/swipes').set(as(d)).send({itemId:x,mode:'SWAP',direction:'RIGHT'}).expect(400);
  await http.post('/swipes').set(as(d)).send({itemId:x,mode:'SWAP',direction:'LEFT'}).expect(201);
  await http.post('/swipes').set(as(d)).send({itemId:x,mode:'SHOP',direction:'RIGHT'}).expect(201);
  assert.equal((await http.get('/saved').set(as(d))).body.length,1);
  await http.delete(`/saved/${x}`).set(as(d)).expect(200);
  assert.equal((await http.get('/saved').set(as(d))).body.length,0);
  const chat=(await http.post('/conversations').set(as(d)).send({itemId:x}).expect(201)).body.id;
  const backdate=()=>db.$executeRaw`UPDATE "Message" SET "createdAt"=now()-interval '1 minute',"updatedAt"=now()-interval '1 minute' WHERE "conversationId"=${chat}`;
  const poll=async()=>{
    const first=await http.get(`/conversations/${chat}/messages`).set(as(d)).expect(200);
    return async()=>(await http.get(`/conversations/${chat}/messages`).set(as(d)).query({since:first.body.cursor}).expect(200)).body.messages as {id:string;offerStatus:string}[];
  };
  const offer=(await http.post(`/conversations/${chat}/offers`).set(as(d)).send({amount:50}).expect(201)).body.id;
  await backdate();
  let next=await poll();
  assert.equal((await next()).length,0);
  await http.post(`/conversations/${chat}/offers/${offer}`).set(as(b)).send({action:'DECLINE'}).expect(201);
  assert.deepEqual((await next()).map(m=>[m.id,m.offerStatus]),[[offer,'DECLINED']]);
  const second=(await http.post(`/conversations/${chat}/offers`).set(as(d)).send({amount:60}).expect(201)).body.id;
  await backdate(); next=await poll();
  const counter=(await http.post(`/conversations/${chat}/offers`).set(as(b)).send({amount:70}).expect(201)).body.id;
  const changed=await next();
  assert.equal(changed.find(m=>m.id===second)?.offerStatus,'COUNTERED');
  assert.equal(changed.find(m=>m.id===counter)?.offerStatus,'PENDING');
  await http.get(`/conversations/${chat}/messages?since=nope`).set(as(d)).expect(400);
  const y=await listing(c,{title:'Match flag item'});
  await http.post('/swipes').set(as(b)).send({itemId:y,mode:'SWAP',direction:'RIGHT'}).expect(201);
  const matched=await http.post('/swipes').set(as(c)).send({itemId:x,mode:'SWAP',direction:'RIGHT'}).expect(201);
  const matchId=matched.body.match.id;
  type Row={id:string;hasChatted:boolean;isNewMatch:boolean};
  const inbox=async()=>((await http.get('/conversations').set(as(c)).expect(200)).body as Row[]).find(r=>r.id===matchId)!;
  assert.deepEqual(await inbox(),{...await inbox(),hasChatted:false,isNewMatch:true});
  await http.post(`/conversations/${matchId}/messages`).set(as(c)).send({text:'Deal?'}).expect(201);
  assert.equal((await inbox()).isNewMatch,false);
  assert.equal(((await http.get('/conversations').set(as(d))).body as Row[]).find(r=>r.id===chat)!.hasChatted,true);
});
